In [4]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import neighbors
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn import preprocessing
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_curve, auc, precision_recall_curve, f1_score, precision_score
from sklearn.ensemble import RandomForestClassifier
import seaborn as sns
from sklearn import model_selection

import numpy as np
from imblearn.over_sampling import *
from imblearn.under_sampling import *

In [5]:
df = pd.read_csv('data.csv')

In [6]:
df['bookingdate'] = pd.to_datetime(df['bookingdate'])
df['creationdate'] = pd.to_datetime(df['creationdate'])
currency_dict = {'MXN': 0.01*0.05, 'SEK': 0.01*0.11, 'AUD': 0.01*0.67, 'GBP': 0.01*1.28, 'NZD': 0.01*0.61}
df['euro'] = map(lambda x,y: currency_dict[y]*x, df['amount'],df['currencycode'])

In [7]:
df.head()

,txid,bookingdate,issuercountrycode,txvariantcode,bin,amount,currencycode,shoppercountrycode,shopperinteraction,simple_journal,cardverificationcodesupplied,cvcresponsecode,creationdate,accountcode,mail_id,ip_id,card_id,euro
0,1,2015-11-09 14:26:51,MX,mccredit,530056.0,64800.0,MXN,MX,Ecommerce,Chargeback,True,0,2015-07-01 23:03:11,MexicoAccount,email68370,ip111778,card184798,<map object at 0x00000295D96CEF98>
1,2,2015-11-09 14:27:38,MX,mccredit,547046.0,44900.0,MXN,MX,Ecommerce,Chargeback,True,0,2015-07-02 04:50:55,MexicoAccount,email101299,ip78749,card151595,<map object at 0x00000295D96CEF98>
2,3,2015-11-23 16:34:16,MX,mccredit,528843.0,149900.0,MXN,MX,Ecommerce,Chargeback,True,0,2015-07-02 14:30:28,MexicoAccount,email278604,ip70594,card242142,<map object at 0x00000295D96CEF98>
3,4,2015-11-23 16:34:51,MX,mccredit,547146.0,109900.0,MXN,MX,Ecommerce,Chargeback,True,0,2015-07-03 07:53:37,MexicoAccount,email47409,ip113648,card181744,<map object at 0x00000295D96CEF98>
4,5,2015-11-09 14:26:08,MX,visaclassic,477291.0,89900.0,MXN,MX,Ecommerce,Chargeback,True,0,2015-07-08 18:35:35,MexicoAccount,email205501,ip83553,card97271,<map object at 0x00000295D96CEF98>

In [8]:
def num_missing(x):
    return sum(x.isnull())

df_renamed = df.rename(index=str, columns = {'txvariantcode': 'cardtype', 'bin': 'issuer_id', 'shopperinteraction': 'shoppingtype',
                   'simple_journal': 'label', 'cardverificationcodesupplied': 'cvcsupply', 
                  'cvcresponsecode': 'cvcresponse', 'accountcode': 'merchant_id'})
# df_select = (df_renamed[['issuercountrycode', 'cardtype', 'issuer_id', 'euro', 'currencycode',
#               'shoppercountrycode', 'shoppingtype', 'label', 'cvcsupply', 'cvcresponse', 'merchant_id',
#               'mail_id', 'ip_id', 'card_id']])
df_select = (df_renamed[['issuercountrycode', 'cardtype', 'issuer_id', 'euro', 'currencycode',
              'shoppercountrycode', 'shoppingtype', 'label', 'cvcsupply', 'cvcresponse', 'merchant_id']])
print "Missing values per column:"
print df_select.apply(num_missing, axis=0)
print "Missing values per row:"
#print df_select.apply(num_missing, axis=1).head()
#df_select.shape
#df_clean = df_select.dropna(axis=0)
df_clean = df_select.fillna('missing')

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Missing values per column:")? (<ipython-input-8-1611e862c311>, line 12)

In [19]:
df_clean.head()

,issuercountrycode,cardtype,issuer_id,euro,currencycode,shoppercountrycode,shoppingtype,label,cvcsupply,cvcresponse,merchant_id
0,MX,mccredit,530056,32.40,MXN,MX,Ecommerce,Chargeback,True,0,MexicoAccount
1,MX,mccredit,547046,22.45,MXN,MX,Ecommerce,Chargeback,True,0,MexicoAccount
2,MX,mccredit,528843,74.95,MXN,MX,Ecommerce,Chargeback,True,0,MexicoAccount
3,MX,mccredit,547146,54.95,MXN,MX,Ecommerce,Chargeback,True,0,MexicoAccount
4,MX,visaclassic,477291,44.95,MXN,MX,Ecommerce,Chargeback,True,0,MexicoAccount

In [20]:
issuercountrycode_category = pd.Categorical(df_clean['issuercountrycode'])
cardtype_category = pd.Categorical(df_clean['cardtype'])
#issuer_id_category = pd.Categorical.from_array(df_clean['issuer_id'])
currencycode_category = pd.Categorical(df_clean['currencycode'])
shoppercountrycode_category = pd.Categorical(df_clean['shoppercountrycode'])
shoppingtype_category = pd.Categorical(df_clean['shoppingtype'])
cvcsupply_category = pd.Categorical(df_clean['cvcsupply'])
merchant_id_category = pd.Categorical(df_clean['merchant_id'])
# mail_id_category = pd.Categorical(df_clean['mail_id'])
# ip_id_category = pd.Categorical(df_clean['ip_id'])
# card_id_category = pd.Categorical(df_clean['card_id'])

issuercountrycode_dict = dict(set(zip(issuercountrycode_category, issuercountrycode_category.codes)))
cardtype_dict = dict(set(zip(cardtype_category, cardtype_category.codes)))
currencycode_dict = dict(set(zip(currencycode_category, currencycode_category.codes)))
shoppercountrycode_dict = dict(set(zip(shoppercountrycode_category, shoppercountrycode_category.codes)))
shoppingtype_dict = dict(set(zip(shoppingtype_category, shoppingtype_category.codes)))
cvcsupply_dict = dict(set(zip(cvcsupply_category, cvcsupply_category.codes)))
merchant_id_dict = dict(set(zip(merchant_id_category, merchant_id_category.codes)))
# mail_id_dict = dict(set(zip(mail_id_category, mail_id_category.codes)))
# ip_id_dict = dict(set(zip(ip_id_category, ip_id_category.codes)))
# card_id_dict = dict(set(zip(card_id_category, card_id_category.codes)))

df_clean['issuercountrycode'] = issuercountrycode_category.codes
df_clean['cardtype'] = cardtype_category.codes
df_clean['currencycode'] = currencycode_category.codes
df_clean['shoppercountrycode'] = shoppercountrycode_category.codes
df_clean['shoppingtype'] = shoppingtype_category.codes
df_clean['cvcsupply'] = cvcsupply_category.codes
df_clean['merchant_id'] = merchant_id_category.codes
# df_clean['mail_id'] = mail_id_category.codes
# df_clean['ip_id'] = ip_id_category.codes
# df_clean['card_id'] = card_id_category.codes
df_clean['label_int'], df_clean['cvcresponse_int']= 0,0
df_clean['label_int'] = map(lambda x:1 if str(x) == 'Chargeback' else 0 if str(x) == 'Settled' else 'unknown', df_clean['label'])
df_clean['cvcresponse_int'] = map(lambda x:3 if x > 2 else x+0, df_clean['cvcresponse'])
#0 = Unknown, 1=Match, 2=No Match, 3=Not checked
df1 = df_clean.ix[(df_clean['label_int']==1) | (df_clean['label_int']==0)]#237036 instances
df1.head()

/usr/local/lib/python2.7/site-packages/ipykernel_launcher.py:38: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

,issuercountrycode,cardtype,issuer_id,euro,currencycode,shoppercountrycode,shoppingtype,label,cvcsupply,cvcresponse,merchant_id,label_int,cvcresponse_int
0,92,3,530056,32.40,2,103,1,Chargeback,1,0,1,1,0
1,92,3,547046,22.45,2,103,1,Chargeback,1,0,1,1,0
2,92,3,528843,74.95,2,103,1,Chargeback,1,0,1,1,0
3,92,3,547146,54.95,2,103,1,Chargeback,1,0,1,1,0
4,92,7,477291,44.95,2,103,1,Chargeback,1,0,1,1,0

In [21]:
# df_input = (df1[['issuercountrycode', 'cardtype', 'issuer_id', 'currencycode',
#               'shoppercountrycode', 'shoppingtype', 'cvcsupply', 'cvcresponse_int', 'merchant_id', 'euro',
#               'label_int']])
df_input = (df1[['issuercountrycode', 'cardtype', 'issuer_id', 'currencycode',
              'shoppercountrycode', 'shoppingtype', 'cvcsupply', 'cvcresponse_int', 'euro',
              'label_int']])
df_input[['issuer_id','label_int']] = df_input[['issuer_id','label_int']].astype(int)
print df_input.dtypes
x = df_input[df_input.columns[0:-1]].as_matrix()
y = df_input[df_input.columns[-1]].as_matrix()

issuercountrycode       int16
cardtype                 int8
issuer_id               int64
currencycode             int8
shoppercountrycode      int16
shoppingtype             int8
cvcsupply                int8
cvcresponse_int         int64
euro                  float64
label_int               int64
dtype: object

In [48]:
TP, FP, FN, TN = 0, 0, 0, 0
x_array = np.array(x)
#x_array = preprocessing.normalize(np.array(x), norm='l2')
enc = preprocessing.OneHotEncoder()
#enc = preprocessing.LabelEncoder()
enc.fit(x_array[:,0:-1])
x_encode = enc.transform(x_array[:,0:-1]).toarray()
min_max_scaler = preprocessing.MinMaxScaler()
x_array[:,-1] = min_max_scaler.fit_transform(x_array[1,-1])
x_in = np.c_[x_encode,x_array[:,-1]]
y_in = np.array(y)
x_train, x_test, y_train, y_test = model_selection.train_test_split(x_in, y_in, test_size = 0.2)#test_size: proportion of train/test data
print "Training date set"
# sampler = RandomUnderSampler(ratio=10)
#sampler = OverSampler(verbose = True)
sampler = SMOTE(ratio='minority', kind='regular')
usx, usy = sampler.fit_sample(x_train, y_train)
# usx, usy = x_train, y_train

Training date set

In [ ]:
def cutoff_predict(clf, x, cutoff):
    return (clf.predict_proba(x)[:,1]>cutoff).astype(int)
scores = []

def custom_score(cutoff):
    def score_cutoff(clf, x, y):
        ypred = cutoff_predict(clf, x, cutoff)
        return f1_score(y, ypred)
        #return precision_score(y, ypred)
    return score_cutoff
for cutoff in np.arange(0.1, 0.9, 0.1):
    clf = LogisticRegression()
    validated = cross_validation.cross_val_score(clf, usx , usy, cv = 10, scoring = custom_score(cutoff))
    scores.append(validated)
sns.boxplot(np.arange(0.1, 0.9, 0.1), scores)
plt.title('F scores for each cutoff setting')
plt.xlabel('each cutoff value')
plt.ylabel('custom score')
plt.show()

In [ ]:
cutoff = 0.6
TP, FP, FN, TN = 0, 0, 0, 0
# clf = LogisticRegression()
# clf = svm.SVC(kernel='poly', degree=3)  
#clf = svm.SVC(probability=True)
# clf = RandomForestClassifier(n_estimators=25, criterion='gini')
clf = neighbors.KNeighborsClassifier(algorithm = 'kd_tree')
#clf = svm.SVC(kernel='sigmoid')  
clf.fit(usx, usy)
#y_predict = clf.predict(x_test)#output label
predict_proba = clf.predict_proba(x_test)
# y_predict = (predict_proba[:,1]>cutoff).astype(int)
false_positive_rate, true_positive_rate, thresholds1 = roc_curve(y_test, predict_proba[:,1])
roc_auc = auc(false_positive_rate, true_positive_rate)
plt.subplot(1, 2, 1)
plt.plot(false_positive_rate, true_positive_rate, 'b', label = 'AUC = %0.2f'% roc_auc)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
#plt.legend('AUC = %0.2f'% roc_auc)
plt.legend(loc="lower right")
precision, recall, thresholds2 = precision_recall_curve(y_test, predict_proba[:,1])
plt.subplot(1, 2, 2)
plt.plot(recall, precision)
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('PR Curve')
for i in xrange(len(y_predict)):
    if y_test[i]==1 and y_predict[i]==1:
        TP += 1
    if y_test[i]==0 and y_predict[i]==1:
        FP += 1
    if y_test[i]==1 and y_predict[i]==0:
        FN += 1
    if y_test[i]==0 and y_predict[i]==0:
        TN += 1
print 'TP: '+ str(TP)
print 'FP: '+ str(FP)
print 'FN: '+ str(FN)
print 'TN: '+ str(TN)

In [ ]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(usx, usy)